/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type DetectionToolResponseBody struct {
	// Detection Tool Name
	Name string `json:"name"`
	// PatchAppliedAt
	PatchAppliedAt time.Time `json:"patchAppliedAt,omitempty"`
}
