/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
	"os"
)

type CveGetCveDetailResponseBody struct {
	// advisory of cve
	Advisories []AdvisoryResponseBody `json:"advisories,omitempty"`
	// created time
	CreatedAt time.Time `json:"createdAt"`
	// Cve ID string of cve
	CveID string `json:"cveID"`
	// cvss of cve
	Cvss **os.File `json:"cvss"`
	// cwes of cve
	Cwes []CweResponseBody `json:"cwes"`
	// envMetricV2 of cve
	EnvMetricV2s []EnvMetricV2ResponseBody `json:"envMetricV2s"`
	// envMetricV3 of cve
	EnvMetricV3s []EnvMetricV3ResponseBody `json:"envMetricV3s"`
	// references of cve
	References map[string]string `json:"references"`
	// secMetric of cve
	SecMetrics []SecMetricResponseBody `json:"secMetrics"`
	// serverOsFamilies of cve
	ServerOsFamilies []string `json:"serverOsFamilies"`
	TmpMetricV2 *TmpMetricResponseBody `json:"tmpMetricV2"`
	TmpMetricV3 *TmpMetricResponseBody `json:"tmpMetricV3"`
	// updated time
	UpdatedAt time.Time `json:"updatedAt"`
}
