/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TaskGetTaskListResponseBody struct {
	Paging *PagingResponseBody `json:"paging,omitempty"`
	// Task list
	Tasks []TaskListResponseBody `json:"tasks,omitempty"`
}
