/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AffectedProcResponseBody struct {
	// AffectedProc Name
	Name string `json:"name"`
	// PID
	Pid string `json:"pid"`
}
