/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ServerTag describes a server tag
type ServerTagResponseBody struct {
	// ID of server tag
	Id int64 `json:"id"`
	// Name of server tag
	Name string `json:"name"`
}
