/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServerUpdatePkgPasteServerRequestBody struct {
	// Kernel Release
	KernelRelease string `json:"kernelRelease,omitempty"`
	// Kernel Version
	KernelVersion string `json:"kernelVersion,omitempty"`
	// Server OS Version
	OsVersion string `json:"osVersion,omitempty"`
	// pkg paste text
	PkgPasteText string `json:"pkgPasteText"`
}
