/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type TaskCommentResponseBody struct {
	// Comment content of TaskComment
	Comment string `json:"comment"`
	// created time of TaskComment
	CreatedAt time.Time `json:"createdAt"`
	// ID of TaskComment
	Id int64 `json:"id"`
	// Type of TaskComment
	Type_ string `json:"type"`
	// updated time of TaskComment
	UpdatedAt time.Time `json:"updatedAt"`
	// UserID of TaskComment
	UserID int64 `json:"userID"`
	// UserName of TaskComment
	UserName string `json:"userName"`
}
