/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NeedRestartProcResponseBody struct {
	// InitSystem of NeedRestartProc
	InitSystem string `json:"initSystem"`
	// Path of NeedRestartProc
	Path string `json:"path"`
	// PID
	Pid string `json:"pid"`
	// ServiceName of NeedRestartProc
	ServiceName string `json:"serviceName"`
}
