/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RoleUpdateRoleRequestBody struct {
	// RoleName of role
	RoleName string `json:"roleName,omitempty"`
}
