/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// EnvMetricV3 describes a envMetricV3
type EnvMetricV3ResponseBody struct {
	// created time
	CreatedAt time.Time `json:"createdAt"`
	// CveID of envMetricV3
	CveID string `json:"cveID"`
	// MA of envMetricV3
	Ma string `json:"ma"`
	// MAC of envMetricV3
	Mac string `json:"mac"`
	// MAV of envMetricV3
	Mav string `json:"mav"`
	// MC of envMetricV3
	Mc string `json:"mc"`
	// MPR of envMetricV3
	Mpr string `json:"mpr"`
	// MS of envMetricV3
	Ms string `json:"ms"`
	// MUI of envMetricV3
	Mui string `json:"mui"`
	// ServerRoleID of envMetricV3
	RoleID int64 `json:"roleID"`
	// ServerRoleName of envMetricV3
	RoleName string `json:"roleName"`
	// updated time
	UpdatedAt time.Time `json:"updatedAt"`
}
