/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PkgCpeGetPkgCpeListResponseBody struct {
	Paging *PagingResponseBody `json:"paging,omitempty"`
	// PkgCpes list
	PkgCpes []PkgCpeListResponseBody `json:"pkgCpes,omitempty"`
}
