/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PkgCpeChildResponseBody struct {
	// AffectedProcess list of package
	AffectedProcs []AffectedProcResponseBody `json:"affectedProcs,omitempty"`
	// CpeID of cpe
	CpeID int64 `json:"cpeID,omitempty"`
	// Cpe URI of cpe
	CpeURI string `json:"cpeURI,omitempty"`
	// crated time of package or cpe
	CreatedAt time.Time `json:"createdAt"`
	// Name of package or cpe
	Name string `json:"name"`
	// New Release of package
	NewRelease string `json:"newRelease,omitempty"`
	// New Version of package
	NewVersion string `json:"newVersion,omitempty"`
	// Package ID of package
	PkgID int64 `json:"pkgID,omitempty"`
	// Release of package
	Release string `json:"release,omitempty"`
	// Repository of package
	Repository string `json:"repository,omitempty"`
	// ServerID of package or cpe
	ServerID int64 `json:"serverID"`
	// updated time of package or cpe
	UpdatedAt time.Time `json:"updatedAt"`
	// Version of package or cpe
	Version string `json:"version"`
}
