/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DetectionMethodResponseBody struct {
	// Detection Method Name
	Name string `json:"name"`
	// ReliabilityScore
	ReliabilityScore int64 `json:"reliabilityScore"`
}
