/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Advisory describes a advisory
type AdvisoryResponseBody struct {
	// AdvisoryID of advisory
	AdvisoryID string `json:"advisoryID"`
	// osFamily of advisory
	OsFamily string `json:"osFamily"`
}
