/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TaskAddTaskCommentRequestBody struct {
	// comment content
	CommentContent string `json:"commentContent"`
}
