/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PkgCpeListResponseBody struct {
	// ApplicationName of library package
	ApplicationName string `json:"applicationName,omitempty"`
	// Cpe FS of cpe
	CpeFS string `json:"cpeFS,omitempty"`
	// CpeID of cpe
	CpeID int64 `json:"cpeID,omitempty"`
	// Cpe URI of cpe
	CpeURI string `json:"cpeURI,omitempty"`
	// crated time of package or cpe
	CreatedAt time.Time `json:"createdAt"`
	// githubPKGID of github pkg
	GithubPkgID int64 `json:"githubPkgID,omitempty"`
	// LibraryPath of library package
	LibraryPath string `json:"libraryPath,omitempty"`
	// libraryPKGID of library pkg
	LibraryPkgID int64 `json:"libraryPkgID,omitempty"`
	// Name of package or cpe
	Name string `json:"name"`
	// NeedRestartProcess list of package
	NeedRestartProcs []NeedRestartProcResponseBody `json:"needRestartProcs,omitempty"`
	// New Release of package
	NewRelease string `json:"newRelease,omitempty"`
	// New Version of package
	NewVersion string `json:"newVersion,omitempty"`
	// Flag of Not fixed yet of package
	NotFixedYet bool `json:"notFixedYet,omitempty"`
	// ossLicense of library package
	OssLicense string `json:"ossLicense,omitempty"`
	// Package ID of package
	PkgID int64 `json:"pkgID,omitempty"`
	// Release of package
	Release string `json:"release,omitempty"`
	// Repository of package
	Repository string `json:"repository,omitempty"`
	// ServerID of package or cpe
	ServerID int64 `json:"serverID"`
	// ServerName of package or cpe
	ServerName string `json:"serverName"`
	// ServerUUID of package or cpe
	ServerUuid string `json:"serverUuid"`
	// updated time of package or cpe
	UpdatedAt time.Time `json:"updatedAt"`
	// Version of package or cpe
	Version string `json:"version"`
	// WordpressPackageStatus of wordpress package
	WordpressPackageStatus string `json:"wordpressPackageStatus,omitempty"`
	// wordpressPKGID of wordpress pkg
	WordpressPkgID int64 `json:"wordpressPkgID,omitempty"`
}
