/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// SecMetric describes a secMetric
type SecMetricResponseBody struct {
	// AR of secMetric
	Ar string `json:"ar"`
	// CR of secMetric
	Cr string `json:"cr"`
	// created time
	CreatedAt time.Time `json:"createdAt"`
	// IR of secMetric
	Ir string `json:"ir"`
	// ServerRoleID of secMetric
	RoleID int64 `json:"roleID"`
	// ServerRoleName of secMetric
	RoleName string `json:"roleName"`
	// updated time
	UpdatedAt time.Time `json:"updatedAt"`
}
