/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ChildTaskResponseBody struct {
	// ApplyingPatchOn of task
	ApplyingPatchOn string `json:"applyingPatchOn,omitempty"`
	// created time of task
	CreatedAt time.Time `json:"createdAt"`
	// CVE ID of task
	CveID string `json:"cveID"`
	// ID of task
	Id int64 `json:"id"`
	// Ignore of task
	Ignore bool `json:"ignore"`
	// Ignore until of task
	IgnoreUntil string `json:"ignoreUntil,omitempty"`
	// MainUserID of task
	MainUserID int64 `json:"mainUserID,omitempty"`
	// MainUserName of task
	MainUserName string `json:"mainUserName,omitempty"`
	// Priority of task
	Priority string `json:"priority"`
	// ServerID of task
	ServerID int64 `json:"serverID"`
	// Status of task
	Status string `json:"status"`
	// SubUserID of task
	SubUserID int64 `json:"subUserID,omitempty"`
	// SubUserName of task
	SubUserName string `json:"subUserName,omitempty"`
	// updated time of task
	UpdatedAt time.Time `json:"updatedAt"`
}
