/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PkgCpeAddCpeRequestBody struct {
	// Cpe Name(cpe uri or cpe format string)
	CpeName string `json:"cpeName"`
	// isURI specifies whether cpeName is in URI format or FormatString format.
	IsURI bool `json:"isURI,omitempty"`
	// ServerID
	ServerID int64 `json:"serverID"`
}
