/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CveListResponseBody struct {
	// advisoryIDs of cve
	AdvisoryIDs []string `json:"advisoryIDs,omitempty"`
	// AllTaskCount of cve
	AllTaskCount int64 `json:"allTaskCount"`
	// created time
	CreatedAt time.Time `json:"createdAt"`
	// Cve ID string of cve
	CveID string `json:"cveID"`
	// cwes of cve
	Cwes []CweResponseBody `json:"cwes"`
	// hasExploit of cve
	HasExploit bool `json:"hasExploit,omitempty"`
	// hasMitigation of cve
	HasMitigation bool `json:"hasMitigation,omitempty"`
	// hasWorkaroundof cve
	HasWorkaround bool `json:"hasWorkaround,omitempty"`
	// Flag of active cve
	IsNotActive bool `json:"isNotActive"`
	// isOwaspTopTen2017 of cve
	IsOwaspTopTen2017 bool `json:"isOwaspTopTen2017"`
	// maxV2 of cve
	MaxV2 float64 `json:"maxV2"`
	// maxV3 of cve
	MaxV3 float64 `json:"maxV3"`
	// NewTaskCount of cve
	NewTaskCount int64 `json:"newTaskCount"`
	// cvss v2 scores of cve
	ScoreV2s map[string]float64 `json:"scoreV2s"`
	// cvss v3 scores of cve
	ScoreV3s map[string]float64 `json:"scoreV3s"`
	// Title of cve
	Title string `json:"title"`
	// topicCount of cve
	TopicCount int64 `json:"topicCount"`
	// topicLastUpdatedAt of cve
	TopicLastUpdatedAt time.Time `json:"topicLastUpdatedAt"`
	// updated time
	UpdatedAt time.Time `json:"updatedAt"`
	// cvss v2 vectors of cve
	VectorV2s map[string]string `json:"vectorV2s"`
	// cvss v3 vectors of cve
	VectorV3s map[string]string `json:"vectorV3s"`
}
