/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Cwe describes a cwe
type CweResponseBody struct {
	// cweID of cwe
	CweID string `json:"cweID"`
	// english summary of cwe
	English string `json:"english"`
	// japanese summary of cwe
	Japanese string `json:"japanese"`
	// owaspTopTen2017 of cwe 
	OwaspTopTen2017 string `json:"owaspTopTen2017,omitempty"`
	// sourceType of cwe
	SourceType string `json:"sourceType"`
}
