/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LockfileGetLockfileListResponseBody struct {
	// Lockfiles list
	Lockfiles []LockfileListResponseBody `json:"lockfiles,omitempty"`
	Paging *PagingResponseBody `json:"paging,omitempty"`
}
