/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PkgCpeDeleteCpeDeprecatedRequestBody struct {
	// cpe ID
	CpeID int64 `json:"cpeID"`
}
