/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TaskUpdateTaskRequestBody struct {
	// applyingPatchOn (YYYY-MM-DD) UTC
	ApplyingPatchOn string `json:"applyingPatchOn,omitempty"`
	// mainUserID of task
	MainUserID int64 `json:"mainUserID,omitempty"`
	// Priority of task
	Priority string `json:"priority,omitempty"`
	// Status of task
	Status string `json:"status,omitempty"`
	// subUserID of task
	SubUserID int64 `json:"subUserID,omitempty"`
}
