/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type TaskListResponseBody struct {
	// advisoryIDs of cve
	AdvisoryIDs []string `json:"advisoryIDs,omitempty"`
	// ApplyingPatchOn of task
	ApplyingPatchOn string `json:"applyingPatchOn,omitempty"`
	// created time of task
	CreatedAt time.Time `json:"createdAt"`
	// CVE ID of task
	CveID string `json:"cveID"`
	// DetectionTools of task
	DetectionTools []DetectionToolResponseBody `json:"detectionTools,omitempty"`
	// hasExploit of cve
	HasExploit bool `json:"hasExploit,omitempty"`
	// hasMitigation of cve
	HasMitigation bool `json:"hasMitigation,omitempty"`
	// hasWorkaroundof cve
	HasWorkaround bool `json:"hasWorkaround,omitempty"`
	// ID of task
	Id int64 `json:"id"`
	// Ignore of task
	Ignore bool `json:"ignore"`
	// Ignore until of task
	IgnoreUntil string `json:"ignoreUntil,omitempty"`
	// MainUserID of task
	MainUserID int64 `json:"mainUserID,omitempty"`
	// MainUserName of task
	MainUserName string `json:"mainUserName,omitempty"`
	// OS Name of server
	OsFamily string `json:"osFamily"`
	// OS Version of server
	OsVersion string `json:"osVersion"`
	// Package And CPE Names of task
	PkgCpeNames []string `json:"pkgCpeNames,omitempty"`
	// Flag of Not Fixed Yet of task
	PkgNotFixedYet bool `json:"pkgNotFixedYet,omitempty"`
	// Priority of task
	Priority string `json:"priority"`
	// ServerRoleID of task
	RoleID int64 `json:"roleID"`
	// ServerRoleName of task
	RoleName string `json:"roleName"`
	// ServerID of task
	ServerID int64 `json:"serverID"`
	// ServerName of task
	ServerName string `json:"serverName"`
	// ServerTags of task
	ServerTags []string `json:"serverTags,omitempty"`
	// ServerUUID of task
	ServerUuid string `json:"serverUuid"`
	// Status of task
	Status string `json:"status"`
	// SubUserID of task
	SubUserID int64 `json:"subUserID,omitempty"`
	// SubUserName of task
	SubUserName string `json:"subUserName,omitempty"`
	// updated time of task
	UpdatedAt time.Time `json:"updatedAt"`
}
