/*
 * Future Vuls Public API
 *
 * Future Vuls Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PkgCpeGetPkgDetailResponseBody struct {
	// AffectedProcess list of package
	AffectedProcs []AffectedProcResponseBody `json:"affectedProcs,omitempty"`
	// crated time of package or cpe
	CreatedAt time.Time `json:"createdAt"`
	// ID of package
	Id int64 `json:"id,omitempty"`
	// Name of package or cpe
	Name string `json:"name"`
	// NeedRestartProcess list of package
	NeedRestartProcs []NeedRestartProcResponseBody `json:"needRestartProcs,omitempty"`
	// New Release of package
	NewRelease string `json:"newRelease,omitempty"`
	// New Version of package
	NewVersion string `json:"newVersion,omitempty"`
	// package status of package
	PackageStatuses map[string]string `json:"packageStatuses,omitempty"`
	// Release of package
	Release string `json:"release"`
	// Repository of package
	Repository string `json:"repository,omitempty"`
	Server *ServerChildResponseBody `json:"server"`
	// updated time of server
	Tasks []ChildTaskResponseBody `json:"tasks,omitempty"`
	// updated time of package or cpe
	UpdatedAt time.Time `json:"updatedAt"`
	// Version of package or cpe
	Version string `json:"version"`
}
